# See: https://github.com/kubernetes-sigs/kubespray/blob/v2.23.0/roles/kubernetes-apps/argocd/tasks/main.yml
---
- name: Custom | ArgoCD | Create directory to store manifests
  file:
    path: "{{ custom_kube_config_dir }}/argocd"
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Custom | ArgoCD | Create manifests from templates
  template:
    src: application.yaml.j2
    dest: "{{ custom_kube_config_dir }}/argocd/application.yaml"
- name: Custom | ArgoCD | Deploy application
  become: true
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ custom_kube_config_dir }}/argocd/application.yaml"
    state: latest
- name: Custom | ArgoCD | Update params configmap
  k8s:
    state: patched
    kind: ConfigMap
    namespace: "{{ argocd_namespace }}"
    name: argocd-cmd-params-cm
    definition:
      data:
        server.insecure: "true" # See: https://argo-cd.readthedocs.io/en/release-2.8/operator-manual/ingress/#option-2-ssl-termination-at-ingress-controller
        server.rootpath: "/argocd"
- name: Custom | ArgoCD | Update configmap
  k8s:
    state: patched
    kind: ConfigMap
    namespace: "{{ argocd_namespace }}"
    name: argocd-cm
    definition:
      data:
        kustomize.buildOptions: --enable-helm # See: https://argo-cd.readthedocs.io/en/release-2.8/user-guide/kustomize/#kustomizing-helm-charts
- name: Custom | ArgoCD | Force recreating pods to use the latest config
  k8s:
    state: absent
    kind: Pod
    namespace: "{{ argocd_namespace }}"
    label_selectors:
      # See: https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.0/manifests/install.yaml
      - app.kubernetes.io/name in (argocd-application-controller, argocd-repo-server, argocd-server)
